[package]
name = "binary_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timed = "0.1.2"
sbx_common = { git = "https://github.com/thesandybridge/sbx_common" }
